### ISSUE TITLE
lack of directions on how to compile project from visual studio.

### ISSUE THREAD

**Issue by LoneWolfGmer** [Lillious/Lethal-Company-Mod-Library#5] opened 2023-12-19 01:12 UTC
as the title says. 
I would appreciate it if you tell peeps it needs to be compiled. well, you don't at all.
but with that in mind. listing directions on how to compile it and what needs to be done, extensions, add-ons, and so forth for the program to compile and build it effectively would be very helpful.  I've been trying to get it to work using the build button on Visual Studio but it does not work it throws a bunch of errors and fails. I've tried saving the repo file as a .dll after importing it to Visual Studio and that fails. without clear directions rather than simply saying it needs to be exported. a simple but to the point set of directions would help a lot for none programmers like myself

**Comment by Lillious** [comment] 2023-12-19 21:56
Duplicate of #4

**Closed as completed by Lillious** 2023-12-19 21:56 UTC

**Comment by LoneWolfGmer** [comment] 2023-12-19 22:16
While it's great to get lazy and such as far as directions to compile and such. All your unwillingness showed is that you want people to wait for a stable .dll file. And refuse to guide anyone how to make it themselves despite saying it needs done manually.

**Comment by Lillious** [comment] 2023-12-20 14:53
Workflow added to auto build nightly alpha releases @LoneWolfGmer
